9oormthon-univ/2024_DANPOONG_TEAM_18_BE

src/main/java/com/memorytree/forest/controller/DiaryController.java
src/main/java/com/memorytree/forest/dto/global/ExceptionDto.java
src/main/java/com/memorytree/forest/dto/global/ResponseDto.java
src/main/java/com/memorytree/forest/dto/request/DiaryAudioRequest.java
src/main/java/com/memorytree/forest/dto/response/DiaryAudioResponse.java
src/main/java/com/memorytree/forest/exception/CommonException.java
src/main/java/com/memorytree/forest/exception/ErrorCode.java
src/main/java/com/memorytree/forest/exception/GlobalExceptionHandler.java

어떤 변경사항이 있었나요?
@ExceptionHandler를 이용한 exception class를 작성했습니다. 
자세한 설명은 아래 링크 참고해주세요
[CLICK](https://velog.io/@hyeondooori_/%EC%8A%A4%ED%94%84%EB%A7%81%EC%9D%98-%EC%98%88%EC%99%B8-%EC%B2%98%EB%A6%AC-%EB%B0%A9%EB%B2%95-%EC%9D%B4%ED%95%B4%ED%95%98%EA%B8%B0ExceptionHandler-ControllerAdvice-%EB%93%B1)
N/A

:sparkles:feat: exception 작성

---

src/main/java/com/memorytree/forest/annotation/UserId.java
src/main/java/com/memorytree/forest/domain/Diary.java
src/main/java/com/memorytree/forest/domain/Game.java
src/main/java/com/memorytree/forest/domain/User.java

#7
어떤 변경사항이 있었나요?
- [x ] ✨ Feature Feature
- [ x] PR 컨벤션에 맞게 작성했습니다. (필수)
- User class 작성
- Diary class 작성
- Game class 작성
- controller에서 사용하기위한 UserId 어노테이션 정의
N/A
컨트롤러 내부 사용방식입니다!

:sparkles: feat: domain class 작성 #7

---

build.gradle
src/main/java/com/memorytree/forest/domain/Diary.java
src/main/java/com/memorytree/forest/domain/Game.java
src/main/java/com/memorytree/forest/domain/User.java

fixed #11 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 작업 내용
N/A
오류로 인한 pr

🐞 BugFix: domain class

---

.gitignore
src/main/resources/application.properties
src/main/resources/application.yml

어떤 변경사항이 있었나요?
각 작업환경별로 `application.yml`을 분리한 후 선택적으로 활성화 가능하도록 변경했습니다.

:rocket: Separate application.yml #13

---

.idea/compiler.xml
.idea/vcs.xml
build.gradle
src/main/java/com/memorytree/forest/annotation/UserId.java
src/main/java/com/memorytree/forest/controller/DiaryController.java
src/main/java/com/memorytree/forest/domain/Diary.java
src/main/java/com/memorytree/forest/dto/request/DiaryAudioRequestDto.java
src/main/java/com/memorytree/forest/dto/request/DiaryTextRequestDto.java
src/main/java/com/memorytree/forest/dto/response/DiaryAudioResponseDto.java
src/main/java/com/memorytree/forest/exception/ErrorCode.java
src/main/java/com/memorytree/forest/exception/GlobalExceptionHandler.java
src/main/java/com/memorytree/forest/repository/DiaryRepository.java
src/main/java/com/memorytree/forest/repository/UserRepository.java
src/main/java/com/memorytree/forest/service/DiaryService.java
src/main/java/com/memorytree/forest/service/UserService.java
src/main/java/com/memorytree/forest/stt/StreamingSpeechRecognizer.java
src/main/java/com/memorytree/forest/stt/SttService.java

resolved #17  
resolved #9 
어떤 변경사항이 있었나요?
- 작업 내용

일기쓰기, 일기쓰기_음성 api  및 stt api 작성

---

.idea/compiler.xml
.idea/vcs.xml
build.gradle
src/main/java/com/memorytree/forest/annotation/UserId.java
src/main/java/com/memorytree/forest/controller/DiaryController.java
src/main/java/com/memorytree/forest/domain/Diary.java
src/main/java/com/memorytree/forest/dto/request/DiaryAudioRequestDto.java
src/main/java/com/memorytree/forest/dto/request/DiaryTextRequestDto.java
src/main/java/com/memorytree/forest/dto/response/DiaryAudioResponseDto.java
src/main/java/com/memorytree/forest/exception/ErrorCode.java
src/main/java/com/memorytree/forest/exception/GlobalExceptionHandler.java
src/main/java/com/memorytree/forest/repository/DiaryRepository.java
src/main/java/com/memorytree/forest/repository/UserRepository.java
src/main/java/com/memorytree/forest/service/DiaryService.java
src/main/java/com/memorytree/forest/service/UserService.java
src/main/java/com/memorytree/forest/stt/StreamingSpeechRecognizer.java
src/main/java/com/memorytree/forest/stt/SttService.java

fixed #9  : 일기쓰기 api 수정
어떤 변경사항이 있었나요?
- error 처리 추가

:sparkles:feat: 일기쓰기 api error처리 추가

---

src/main/java/com/memorytree/forest/controller/DiaryController.java

fixed #9  : controller부분  핫 픽스 이슈
어떤 변경사항이 있었나요?
- controller부분에 없는 Response사용 코드 제거

:bug:Hotfix: 일기쓰기 api controller 오류수정 #9

---

src/main/java/com/memorytree/forest/controller/MissionController.java
src/main/java/com/memorytree/forest/domain/Game.java
src/main/java/com/memorytree/forest/dto/response/GameRecordDto.java
src/main/java/com/memorytree/forest/dto/response/MissionDto.java
src/main/java/com/memorytree/forest/repository/GameRepository.java
src/main/java/com/memorytree/forest/service/MissionService.java

closed #16 : 미션 수행 여부 + 게임 최고 기록 조회
어떤 변경사항이 있었나요?
남은 미션 수 대신 미션 수행 현황을 `Boolean`으로 나타내도록 작성했습니다.
게임 최고기록 리포지토리를 조회하여 관련된 엔티티를 가져오고, 각 필드를 `GameRecordDto`로 변경하여 제공하도록 작성했습니다.

:sparkles: 미션 수행 현황 및 게임 기록 조회 #16

---

.github/workflows/github-actions.yml

어떤 변경사항이 있었나요?
- CICD 구현을 위한 github-actions.yml파일을 작성했습니다.
N/A

:sparkles:feat: 배포 관련 actions 파일 작성

---

.gitignore
src/main/java/com/memorytree/forest/domain/Game.java

어떤 변경사항이 있었나요?
YML을 환경변수로 넘겨줄 예정이라, gitignore에 application.yml도 무시되게 바꾸었습니다!

:recycle:refactor: 배포 관련 .gitignore 수정

---

.github/workflows/github-actions.yml
src/main/resources/application.properties

어떤 변경사항이 있었나요?
- github-actions 파일 내부에 build 실행 명령어에 권한 부여

:bug:fix: actions update

---

.github/workflows/github-actions.yml

어떤 변경사항이 있었나요?
- actions파일 내부 포트번호 지정 코드 수정
N/A

:bug:Hotfix!: actions update

---

src/main/java/com/memorytree/forest/controller/GameController.java
src/main/java/com/memorytree/forest/controller/MissionController.java
src/main/java/com/memorytree/forest/domain/Game.java
src/main/java/com/memorytree/forest/dto/request/GameResultRequestDto.java
src/main/java/com/memorytree/forest/dto/response/GameResultResponseDto.java
src/main/java/com/memorytree/forest/dto/response/GameType.java
src/main/java/com/memorytree/forest/service/GameService.java

feat: #28 
어떤 변경사항이 있었나요?
- Game 도메인과 관련된 MVC패턴 구현
- 게임 요청 기능과 게임 결과 업로드 기능을 구현

:sparkles: feat: 랜덤 게임 요청 및 게임 최고 기록 갱신 기능 #28

---

.github/workflows/github-actions.yml
.gitignore
Dockerfile-dev
build.gradle
src/main/java/com/memorytree/forest/controller/DiaryController.java
src/main/java/com/memorytree/forest/domain/Game.java
src/main/java/com/memorytree/forest/domain/User.java
src/main/java/com/memorytree/forest/dto/request/DiaryAudioRequest.java
src/main/java/com/memorytree/forest/dto/response/DiaryAudioResponse.java
src/main/java/com/memorytree/forest/dto/response/DiaryQuizAnswerResponseDto.java
src/main/java/com/memorytree/forest/dto/response/DiaryQuizResponseDto.java
src/main/java/com/memorytree/forest/exception/ErrorCode.java
src/main/java/com/memorytree/forest/repository/DiaryRepository.java
src/main/java/com/memorytree/forest/service/DiaryService.java
src/main/resources/application.properties

closed #10  
어떤 변경사항이 있었나요?
- 일기를 최소 4번 이상 작성해야만 일기 기반 질문이 생성됩니다.
- 랜덤함수를 이용해서 4가지 필드(who,when,where,what)중에  한가지를 고릅니다.
- 일기의 3가지 필드 정보를 제공하고, 나머지 한 정보를 객관식으로 맞추게 됩니다.
- 객관식의 보기들은 전부 지난 일기들에 기록했던 정보들로 구성됩니다.
- 일기는 하루에 한 번만 쓸 수 있습니다.

✨ feat: 기억되짚기 질문 생성 및 응답 검증 api 작성

---

.idea/misc.xml
build.gradle
src/main/java/com/memorytree/forest/config/WebConfig.java
src/main/java/com/memorytree/forest/controller/DiaryController.java
src/main/java/com/memorytree/forest/domain/User.java
src/main/java/com/memorytree/forest/exception/ErrorCode.java
src/test/java/com/memorytree/forest/ForestApplicationTests.java

closed #9 
어떤 변경사항이 있었나요?
- [x ] PR 컨벤션에 맞게 작성했습니다. (필수)
- [x ] Docker Container 환경으로 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트). (필수)
- [x ] Feature의 경우, API 문서 업데이트를 완료했습니다. (선택)
- [x ] BugFix의 경우, 버그의 원인을 파악하였습니다. (선택)
- null이 될 수 있는 정수값은 int 말고 Integer 사용해야함을 알았다.
N/A

:recycle:refactor: test완료

---

src/main/java/com/memorytree/forest/domain/Game.java
src/main/java/com/memorytree/forest/service/KakaoOAuthService.java

없음
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 작업 내용

:bug: fix: create game entity when user created

---

src/main/java/com/memorytree/forest/controller/GameController.java
src/main/java/com/memorytree/forest/controller/MissionController.java
src/main/java/com/memorytree/forest/controller/SettingController.java
src/main/java/com/memorytree/forest/service/MissionService.java

어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 작업 내용

:bug: fix: last game played date null check and setting url prefix 

---

src/main/java/com/memorytree/forest/domain/Game.java
src/main/java/com/memorytree/forest/service/GameService.java
src/main/java/com/memorytree/forest/service/UserService.java

어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 작업 내용

:bug: fix: remove default value of game highscore

---

src/main/java/com/memorytree/forest/service/DiaryService.java

fixed #9 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 작업 내용

:sparkles:feat: addEXP in diary wrote and quiz complete

---

src/main/java/com/memorytree/forest/controller/homeController.java
src/main/java/com/memorytree/forest/dto/response/HomeResponceDto.java
src/main/java/com/memorytree/forest/dto/response/diaryAudioResponse.java
src/main/java/com/memorytree/forest/service/UserService.java

어떤 변경사항이 있었나요?
- home api구현
N/A

:sparkles:feat: home api

---

src/main/java/com/memorytree/forest/config/SecurityConfig.java

어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 작업 내용

:bug: fix: disable CORS

---

src/main/java/com/memorytree/forest/config/SecurityConfig.java

어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 작업 내용

:bug: fix: allow origin/method/header all for CORS

---

build.gradle
src/main/java/com/memorytree/forest/config/SecurityConfig.java
src/main/java/com/memorytree/forest/config/WebMvcConfig.java
src/main/java/com/memorytree/forest/controller/KakaoOAuthController.java
src/main/java/com/memorytree/forest/service/KakaoOAuthService.java

어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 작업 내용

:bug: fix: use custom controller instead of oauth2client

---

src/main/java/com/memorytree/forest/config/SecurityConfig.java

어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 작업 내용

:bug: fix: allow url pattern '/api/**'
